version: 2.1

orbs:
  unity: game-ci/unity@0.2.2

jobs:
  build_asset_bundles:
    docker:
      - image: cimg/base:stable
    steps:
      - unity/prepare-env
      - checkout
      - run:
          #working_directory: ~/project/App.Tests
          name: Build Asset Bundles
          command: |
            /Applications/Unity/Hub/Editor/2022/Unity.app/Contents/Linux/Unity -batchmode -projectPath "./" -executeMethod CustomUnityCli.BuildAssetBundles -quit -logFile /dev/stdout
      - run:
          #working_directory: ~/project/App.Tests
          name: Upload Assetbundles
          command: |
            python3 upload_asset_bundles.py
    
workflows:
  asset-bundles-workflow:
    jobs:
      - build_asset_bundles