version: 2.1

executors:
  unity_exec:
    docker:
      - image: gableroux/unity3d:2018.4.5f1-android
    environment:
      BUILD_NAME: my_build_name

.build: &build
  executor: unity_exec
  steps:
    - checkout
    - run: 
        name: step 1
        command: /Applications/Unity/Hub/Editor/2022/Unity.app/Contents/Linux/Unity -batchmode -projectPath "./" -executeMethod CustomUnityCli.BuildAssetBundles -quit -logFile /dev/stdout
    - run:
        name: step 2
        command: python3 upload_asset_bundles.py
    # - run: 
    #     name: Zipping build
    #     command: apt update && apt -y install zip && zip -r "build.zip" ./Builds/
    # - store_artifacts:
    #     path: build.zip
jobs:
  build_android:
    <<: *build
    environment:
      BUILD_TARGET: Android
          
workflows:
  version: 2
  build:
    jobs:
      - build_android