# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  unity: game-ci/unity@1.3.0
  #win: circleci/windows@4.1.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  download-skp-file:
    #executor: win/default
    #macos:
    #  xcode: 14.1.0
    docker:
      - image: cimg/base:stable
    steps:
      - store_artifacts:
          path: /tmp
      #- checkout
      - run:
          name: "Download skp file"
          command: |
            export SKP_FILE_NAME=$(curl -s 'https://firebasestorage.googleapis.com/v0/b/condominium-unity.appspot.com/o/' | jq '.items[0].name' | tr -d '"')
            export SKP_FILE_TOKEN=$(curl -s "https://firebasestorage.googleapis.com/v0/b/condominium-unity.appspot.com/o/${SKP_FILE_NAME}" | jq '.downloadTokens' | tr -d '"')
            echo "https://firebasestorage.googleapis.com/v0/b/condominium-unity.appspot.com/o/${SKP_FILE_NAME}?alt=media&token=${SKP_FILE_TOKEN}"
            echo "export FILE_NAME=$SKP_FILE_NAME" >> $BASH_ENV
          #  curl -o "./Assets/Resources/Models/Buildings/$SKP_FILE_NAME" "https://firebasestorage.googleapis.com/v0/b/condominium-unity.appspot.com/o/${SKP_FILE_NAME}?alt=media&token=${SKP_FILE_TOKEN}"
      - unity/build:
            build-target: StandaloneLinux64
            build-method: CustomUnityCli.BuildAssetBundles
            custom-parameters: $FILE_NAME
            compress: false
            project-path: .
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  generate-asset-bundle-workflow:
      jobs:
        - unity/create-activation-file:
            name: "create-activation-file"
        - download-skp-file
        #- unity/build:
        #    name: "Build Asset Bundles"
        #    build-target: StandaloneLinux64
        #    build-method: CustomUnityCli.BuildAssetBundles
        #    custom-parameters: $FILE_NAME
        #    compress: false
        #    context: cpe-unity
        #    project-path: .
        #    executor:
        #      name: unity/ubuntu
        #      target_platform: "linux-il2cpp"
        #      editor_version: 2021.3.1f1
        #      resource_class: medium
        #    unity-license-var-name: UNITY_ENCODED_LICENSE 
        #    unity-password-var-name: UNITY_PASSWORD 
        #    unity-username-var-name: UNITY_USERNAME